<?php
/**
 * Secure Credential Portal — Configuration
 *
 * SETUP STEPS:
 *  1. Run `node keygen.js` in your terminal to generate a keypair.
 *  2. Paste the public key (base64) into RSD_PUBLIC_KEY_B64 below.
 *  3. Store the private key somewhere safe and offline — never upload it.
 *  4. (Optional) Move RSD_DATA_FILE path above your public_html root in cPanel
 *     e.g. '/home/YOUR_CPANEL_USER/secure_data/submissions.json'
 */

// Your RSA-OAEP public key (SPKI, base64). Generated by keygen.js. Safe to embed here.
// Note: this will be a long string (~800 chars) — that's normal for a 4096-bit RSA key.
define('RSD_PUBLIC_KEY_B64', 'MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAofo1iZ9bFUOlFHGw6o3ay9RPLhqB3ke5JN9uY6TQQimAiOmFQalkahg2J0JOTcnZ6Z+ueWthREDC/hWjfA7NTVKmjCCuMQoExDOfpZU+WnqltiROrvs3mti6+zrk/PklJeNCexZzpPKJGDqrMKkdg4kHajACDck+s65aTnH8lHWXuT4ew0jK6hwmepHeGpuxsRSAGlbAUM8LB22l6xlAO+zWktR5e3Xl5oq7CIrLLZWG+x6IDfaWljJ39pzOYwlhjJEvLtAJ9RDJoNNyIDIi7fTM+aDnvXQqkEdYhsUVrMUyYHPLSCmQUmvhUe0BvKHbeWOrxBh63OrVTzmqKpemy5eeQb5quhultofE104zs6O78UI+dg/S0h0dQQN9Qsf0PUMN9fukrBZ6Vle/6pj2fl3KEXtF2MCNz6NXqo3H/Jvv1WrCYB3Gdb32KdsN9aczK2LWKZvT8mX9tMb0Oi7/U68OIaA5pmmg0r7+zjwBS/zVY/mdnJOWdtnsqUDBLhfC2/hjEEncYIElPdfuAlA7/4bfUNcURga1Y3PpQvECGboEdPBxG5AjoYpU3N+46pgJHbRQDL6XIGQs/tu8n+fYJ7PEXKRJLPdX6QNLeHPjPaEMN9zEeivyv8DVCoxU0ldkH4j/aaStcsL+Leb5gyR5phu3OPbiywXweyOwg6QE4N8CAwEAAQ==');

// Path to the submissions data file.
// Default: portal/data/submissions.json — protected by .htaccess.
// Recommended: move above public_html in cPanel for better isolation,
// e.g. '/home/YOUR_CPANEL_USER/secure_data/submissions.json'
define('RSD_DATA_FILE', __DIR__ . '/data/submissions.json');
